### ISSUE TITLE
HW Agent - Add the Auth Type Credentials to the Openstack Plugin

### ISSUE THREAD

**Issue by agimenobono** [aiondemand/AIOD-HW-agent#14]
**Describe the Feature**
Add as a new type of authentication the v3applicationcredential, supported explicitly by the clouds configuration file in OpenStack. This authentication method allows users to authenticate using Application Credentials

**An Example**
```yaml
clouds:
  mycloud:
    auth:
      auth_type: v3applicationcredential
      auth_url: "https://openstack.example.com/v3"
      application_credential_id: "123456789abcdef"
      application_credential_secret: "application-secret"
```
